//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENSE
    {
        public int idJourney { get; set; }
        public int idMember { get; set; }
        public int id { get; set; }
        public string objectPay { get; set; }
        public Nullable<int> cost { get; set; }
    
        public virtual MEMBER MEMBER { get; set; }
    }
}
