//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WESPLITEntities : DbContext
    {
        public WESPLITEntities()
            : base("name=WESPLITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EXPENSE> EXPENSEs { get; set; }
        public virtual DbSet<IMAGE_DESTINATION> IMAGE_DESTINATION { get; set; }
        public virtual DbSet<JOURNEY> JOURNEYs { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
